### ISSUE TITLE
different directory used in different places

### ISSUE THREAD

**Issue by cooktheryan** [redhat-et/ceph-mirroring#1]
The directory ceph-deployment and rook-ceph-mirroring are used interchangeably throughout the document. One of them should be removed.

**Comment by screeley44** [comment]
merge the directories and keep consistent throughout readme

**Comment by screeley44** [comment]
removed directory *rook-ceph-mirroring*
removed all references in the readme to *rook-ceph-mirroring*
Updated storage-schedule.md

closing this issue
